App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
    country:
      - NotBlank:
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -90
          max: 90
          groups: ['create', 'edit']

App\Entity\Forecast:
  properties:
    date:
      - NotBlank:
          groups: ['create', 'edit']
    temperature:
      - NotNull:
          groups: ['create', 'edit']
      - Range:
          min: -20
          max: 40
          groups: ['create', 'edit']
    pressure:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: 965
          max: 1054
          groups: ['create', 'edit']
    windSpeed:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: 20
          max: 200
          groups: ['create', 'edit']